// flow-typed signature: 3b6f822563798ad85aeaaf93ad94d835
// flow-typed version: <<STUB>>/next-redux-wrapper_v^1.2.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-redux-wrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-redux-wrapper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-redux-wrapper/src/index' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/src/index.server.spec' {
  declare module.exports: any;
}

declare module 'next-redux-wrapper/src/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-redux-wrapper/src/index.js' {
  declare module.exports: $Exports<'next-redux-wrapper/src/index'>;
}
declare module 'next-redux-wrapper/src/index.server.spec.js' {
  declare module.exports: $Exports<'next-redux-wrapper/src/index.server.spec'>;
}
declare module 'next-redux-wrapper/src/index.spec.js' {
  declare module.exports: $Exports<'next-redux-wrapper/src/index.spec'>;
}
